### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by SteveVaneeckhout** [MewsSystems/public#1]
The Dutch translation for the month October is spelled wrong. It should be: oktober

Also, don't put a `.` behind the day number.

**Comment by jirihelmich** [comment]
Hi. could you be, please, more specific, where you encountered this?

**Comment by SteveVaneeckhout** [comment]
Right, the url is https://www.mews.li/distributor/edge/distributor-app.js
Line 2122

It would be easier if you guys put these files on Github too. What's the use of Github if you don't put your code here?

**Comment by jirihelmich** [comment]
Hi,

as we have more products, I did not know, what product/API you are talking about.

OK, so it's about Distributor. This repository is so far for publishing documentation for all our APIs only.

Currently, we don't plan to move our code to a public repository, for multiple reasons, including the fact that they are not served from GitHub and there is no use in having a copy here.

We also do not provide support here, however, we already fixed the translation and track an issue for the indwelling dot. Those fixes will be in an upcoming release (no specific date so far).

If you have any more questions or bugs to report, please, contact our support at support@mewssystems.com or file a ticket at https://mews.desk.com/ .

Anyway, thank you for your feedback
