### ISSUE TITLE
Process Reservation - missing required request property?

### ISSUE THREAD

**Issue by wayne530** [MewsSystems/public#11]
Hi, according to the documentation here:
http://mewssystems.github.io/public/content/developers/api/connector.html#process-reservation

The request object should require just a `Reservation`. However, when attempting to make a request with just the `ReservationId`, I get an error back from the API:

`{"Details":null,"Message":"Please fill in the reason."}`

Is there a `Reason` or `Note` field that is required, but not represented in the request object documentation for this endpoint? Thanks in advance for your help!

**Comment by jirihelmich** [comment]
Hi, could you provide us with a sample request? E.g. in form of a cURL command? This could be a bug, I would like to investigate it.

**Comment by onashackem** [comment]
I am sorry @wayne530, this was my mistake. I have fixed it and deployed it, so you can continue now.

**Comment by wayne530** [comment]
@onashackem Thanks, it's working per the documentation now!
