### ISSUE TITLE
Rate Calculation Clarification

### ISSUE THREAD

**Issue by mbingen** [MewsSystems/public#12]
Hi there,

   We are a bit confused about how to calculate the Rate for a room, based on the data provided in the API. Specifically, when we get a response back from the "Get Rate Pricing" call, we see BasePrices and CategoryPrices (along with some dates), and we aren't exactly sure how that all fits together, semantically. Could you please clarify how we calculate the Rate paid by the Guest for their Stay in the property?

Currently our understanding is that we should 1) get the RequestedCategoryId returned by the "Get All Reservations" call, 2) get the Rates from the "Get Rate Pricing" API, and 3) sum the "base price" with the "category price" for the CategoryId matching our RequestedCategoryId, and it seems that all of this is tied to the dates listed in the DatesUtc field.

Is that correct? Anything you could say to clarify this would be quite helpful. Thank you! 🎄

**Comment by matthijswelle** [comment]
Thanks for your question!

From your message its not clear what type of system you are trying to integrate in to Mews, would you be able to give some more details?

Yes we do not return the rate of the reservation via the "GetAllReservations" call, and you would have to run a separate call to obtain this part of the booking. From the "GetAllReservations" you get a list of the Reservation ID's, with which you can query the "Get All Reservation Items" call.

Via that call we return all the items linked with the reservation, such as the rate, but also any products that are linked to the booking (such as breakfast).

Should you wish to set up a call with someone in our team, let us know and @MeissnerJan will be your go-to person here at Mews. (jan@mewssystems.com)

Have a great weekend,
Matt

**Comment by jirihelmich** [comment]
I would just add that if you are interested in particular spendings related to reservations, you should use the Get All Reservation Items operation: http://mewssystems.github.io/public/content/developers/api/connector.html#get-all-reservation-items
