### ISSUE TITLE
GTM does not track ecommerce with Merchant integration

### ISSUE THREAD

**Issue by pbambusek** [MewsSystems/public#20]
The e-commerce tracking is not working. Below the list of the reservations done via booking widget and data from e-commerce google analytics for the same period. No reservations were tracked.

![ce781b92-2903-11e7-8e98-18ecba9059fb](https://cloud.githubusercontent.com/assets/1269023/25899665/ff1548f8-3590-11e7-81be-30228a849068.png)

**Comment by pbambusek** [comment]
I can see that a GTM container id is being used on a website is `GTM-KN4WMZH`, with analytics tracking id configured to `UA-2183242-40` in transaction tag. Are you sure that it's the same container you're reviewing for a missing transactions?

As far as I can see, the ecommerce tracking does work on mentioned container.

**Comment by arekpiech** [comment]
Hi Petr, you were right - gtmContainerId was wrong. After the proper setup, transactions started being tracked. There is one more thing though: on entering mews.li during checkout, the original source of visit is lost. I guess something is wrong with cross-domain tracking config in Tag Manager, redirection to mews.li is treated as a new session with source "direct". In Universal Analytics Tag Configuration I set allowLinker to "true" and supplied a list of domains to Auto-link (our domain and mews.li), but apparently it is not working.
![e-commerce](https://cloud.githubusercontent.com/assets/28923956/26404141/18a555b4-4091-11e7-8c56-357a8f7a625f.jpg)

**Comment by jirihelmich** [comment]
Hi,

glad to see this working!

The checkout is planned to be implemented without the need of redirect from
your domain very soon. Therefore we do not plan fixing this issue.

Hope you understand.

Thanks!

**Comment by arekpiech** [comment]
Good to know :) May I ask what the E.T.A. of this new implementation might be? Roughly I mean, is it closer to one week, one month, more? Thanks!

**Comment by jirihelmich** [comment]
Hello, unfortunately, we do not share specific dates or estimates (you
know, how it goes with estimates, right?). I can only tell that it's at the
top of our list.

Thanks,
Jirka

**Comment by arekpiech** [comment]
Yeah, I know - still waiting for Half Life 3 ;) Good luck with your work then!

**Comment by arekpiech** [comment]
Sure, thanks.
