### ISSUE TITLE
GTM Facebook Pixel and AdWords configuration

### ISSUE THREAD

**Issue by pbambusek** [MewsSystems/public#26]
Moved from #19 

> written by @crosenbech:
> Hi Petr, you now have access to Urban Houses tag manager. Please take a look at the setup and edit whatever needs to be done

**Comment by pbambusek** [comment]
@crosenbech Please, always start a new issue for a new problem, don't just put totaly unrelated comments into a random issue.

For the sake of the issue, can you describe the problems you're experiencing? From first peek I took, it looks like you want to use data layer variables in those 2 tags, but you don't reference them properly. Is that the problem?

**Comment by crosenbech** [comment]
@pbambusek hi. Sorry - I was of the understanding that you had a talk with Edith from Urban House about setting up the tag manager for them so it would work correctly with your booking tracking.
But yes, if they are not setup correctly and you can see why, please change it so it works :)
thank you!

**Comment by Maksym1** [comment]
Hi @crosenbech , I will just jump in here as I was handling call with Edith:-)
It was agreed during the call that Petr from our side will get logins to your GTM in order to identify possible mistakes in setup and highlight them to you, so it will be sorted out asap. Unfortunately, our developers or not authorised to provide changes to 3rd party tools. Is it OK with you to process it with Petr's guidance?
Thank you very much for understanding!

**Comment by pbambusek** [comment]
@crosenbech It's pretty easy to fix it. As I understand it, you want to reference data layer variables provided by Distributor in the tags, however you haven't defined them. As you can see on the screenshot, what you're actually doing is putting a string value 'totalCost' in the field, not the content of the variable.

![bez nazvu](https://user-images.githubusercontent.com/1269023/27089188-f71f1a0a-5059-11e7-8503-0e6ac44dab1e.png)

You've already done this for the `hotelName` as I can see in the container. Doing this for `totalCost` and `currencyCode` is the same.

If you click on the button in blue, it will lead you to Variables screen, where in top right corner you can add new.  As a variable type, select Data Layer variable. As a name, write the name i.e. `totalCost`.

Now when you want to reference the variable, you have to write it in `{{...}}`, i.e. `{{totalCost}}`. When you're typing this into the configuration field of the tag, an autocomplete should whisper this for you.

You can use this reference in the custom script tag too. GTM will notify if you reference it wrong.

Also, I'd suggest using Preview mode for testing. If you turn it on, it will cookie your browser and when you go to the website using the container, it will display a debug overlay for you so you can confirm that the tags work.

**Comment by crosenbech** [comment]
Amazing! Very nice walkthrough:)
Could you maybe take a last look at both AdWords and Facebook and see if I understand you correctly? I am in no way a tag manager "guy".

Thank you!!

**Comment by pbambusek** [comment]
Looks ok. One last thing I'd suggest is to set the ecommerce tag to trigger only on the booking finished event same as the facebook pixel, as it has no effect on any other event.

Otherwise it seems to be working now.

**Comment by crosenbech** [comment]
Thank you for checking again. But I do not think it is working as it should. I can see that there was 1 conversion in AdWords yesterday - but I cant see the conversion in AdWords only in Analytics.

**Comment by pbambusek** [comment]
Sorry @crosenbech but this is out of my scope. It's about your configuration of the 3rd party services you use and you're responsible for. Distributor is sending those data correctly, and GTM is receiving them correctly, aren't they?

>  I can see that there was 1 conversion in AdWords yesterday

So it does work or not?

> but I cant see the conversion in AdWords only in Analytics.

I really don't understand this sentence, though I guess it's the missing comma that complicates it. I don't know exactly how those tools work, but they don't have to always track in real-time. Do you have both account linked correctly? I'm not sure how this is connected to Distributor at all.

**Comment by Maksym1** [comment]
@crosenbech based on my today's call today with Edith, she told me that everything is working for you now. Could you please confirm it, so we can close this issue? Thank you.

**Comment by crosenbech** [comment]
Hi @Maksym1 I can now confirm that I am seeing the correct data on all platforms and ads.
Thank you very much for the help.

Please close this

**Comment by Maksym1** [comment]
Great! Happy to hear that it works!:-)
