### ISSUE TITLE
Error when trying to use distributor.showRates()

### ISSUE THREAD

**Issue by jngs** [MewsSystems/public#27]
Hello,
We are integrating your distributor widget (https://www.mews.li/distributor/edge/distributor.min.js) to our client’s website and it was working last Friday but today it throws this error:
We are sorry, an unexpected error has occurred. If it happens again, please contact us directly by email at support@mewssystems.com.

URL: not public yet (I sent source files to support@mews.desk-mail.com)
Browser: Google Chrome Version 58.0.3029.110 (64-bit)
I’m also sending error log here.
[distributor.log.zip](https://github.com/MewsSystems/public/files/1074809/distributor.log.zip)

The code used that results to this error is this:

```javascript
   openForm: function () {
     this.isLoading = true
     var hotel = this.getById(this.hotels, this.selectedHotel)
     if (!this.valuesAreValid) {
       return
     }
     console.log('loading distributor...')
     hotelId = hotel.guid
     roomIds = this.rooms.filter(function (room) {
       return room.hotel == hotel.id
     }).map(function (room) {
       return room.guid
     })
     Mews.Distributor({
       hotelId: hotelId,
       language : 'en-US',
       analyticsTrackingId : 'UA-38624119-11',
       gtmContainerId: 'GTM-M9S9CMZ',
       braintree: true,
       language: 'en-EN',
       ecommerce: true,
       loadOverlayCss: true,
       loadCss: true,
       fragments: true,
       hashEvents: true,
       rooms: roomIds,
     }, function(distributor) {
       console.log('loaded distributor', hotelId, roomIds, this.selectedRoom)
       this.isLoading = false
       window.distributor = distributor
       distributor.setStartDate(this.dateFrom)
       distributor.setEndDate(this.dateTo)
       distributor.open()
       distributor.showRates(this.selectedRoom)
     }.bind(this))
   }
```

Hotel IDs are: 60bddec3-02e9-44f1-9a40-6675e7634cd2, c89c518f-5274-47f6-b143-bb1d2d571c05
Room IDs are: b8386aad-d192-4c4b-9b0e-4349f1f901dc, a7ad8596-bd6e-48b1-8f7c-c3ff662ba75d, de80540c-1e93-4cf3-b00b-a705716e55d3, 8ab3fa19-3b8b-4561-a2e3-03d14f3cc60e, 38ed798a-c732-4c79-95e2-584d9fd4d856, 49695b04-2a68-45b6-bbe3-ec68231effbe

Please can you help me with this issue?

**Comment by pbambusek** [comment]
Hi, first of all I'd suggest to follow our documentation for latest options overview. Those you're currently using are from about 3 year old previous generation app version and are unnecessary cluttering the code with zero effect. You can find the reference here: https://mewssystems.github.io/public/content/developers/distributor/widget/reference.html

I've taken a look at your example and it triggers a bug in the code we're already solving. It should be fixed with the next deploy.

**Comment by pbambusek** [comment]
It has been fixed. Changelog here: https://mewssystems.github.io/public/content/developers/distributor/widget/changelog.html#14062017
