### ISSUE TITLE
An unexpected error has occurred

### ISSUE THREAD

**Issue by devbymike** [MewsSystems/public#28]
I've implemented the most basic implementation here http://docklandslodgelondon.co.uk/index-test.html on our main book button in the header. However, each attempt to launch the mews overlay results in a message about an unexpected error. And your server seems to be responding with 404 requests
 
http://docklandslodgelondon.co.uk/index-test.html
Chrome 58.0.3029.110 (64-bit)

Click "BOOK NOW" in the main header, the error will be produced.
 
![developer_tools_-_http___docklandslodgelondon_co_uk_index-test_html_rand_0_6226240576734747_and_docklandslodgelondon_co_uk_index-test_html_rand_0_6226240576734747_](https://user-images.githubusercontent.com/6597660/27353482-65e6b18e-55c1-11e7-834f-5716c2717468.jpg)

![not-working](https://user-images.githubusercontent.com/6597660/27353528-8bfa67f8-55c1-11e7-8ca4-d456f2bfca4b.gif)

**Comment by jirihelmich** [comment]
Hi, actually, one of the requests, the first one, returns 400 - Bad request with message ""There was an error deserializing the object of type Mews.Server.Api.Web.Distributor.V1.Dto.MultipleHotelParameters. The value 'ccarey' cannot be parsed as the type 'Guid'."

ccarey is not a valid hotel id.

Fixing that will solve the issue.
