### ISSUE TITLE
Connection of the Google Tag Manager to the Distributor for Revier Mountain Lodge Lenzerheide

### ISSUE THREAD

**Issue by JoannaSvehlova** [MewsSystems/public#48]
Our e-Marketing person is trying to connect the Google Tag Manager to the Distributor.
It still doesn't work quite like it's supposed to, who can I pass on as a contact for support on this topic?
 

 
- **URL**: 
- **Browser (version)**: 
- **Steps to reproduce**: 
1. 
2. 
3. 
4. 
5.

**Comment by siroky** [comment]
@JoannaSvehlova The person who has an issue is supposed to create it here. Not you.

**Comment by JoannaSvehlova** [comment]
I know, but it is easier for them just to add the comments, therefore I have sent them (hotel) link directly 
to already created issue asking them to update it with the comments they have. Could you reopen pls? I have sent them the link some time ago...
