### ISSUE TITLE
Issue setting up Mews Distributor

### ISSUE THREAD

**Issue by mariokubik** [MewsSystems/public#49]
We are currently working with Kasteel to set up their Mews Distributor, but their web developer has stumbled on this error message. Could you and your developer have a look at this and advise a response? 
 
![1](https://user-images.githubusercontent.com/20040347/29160927-79312de4-7db4-11e7-995e-e27eedc72e41.png)

**Comment by pbambusek** [comment]
It works for me now, I'd suspect that it was connected to the today hotfixes.
