### ISSUE TITLE
Update Customer

### ISSUE THREAD

**Issue by wayne530** [MewsSystems/public#9]
Hi there, can you let me know if the Customer's `Gender` and `Email` are immutable? The documentation located here http://mewssystems.github.io/public/content/developers/api/connector.html#update-customer does not include properties for `Gender` and `Emai`l in the request object. I imagine it's just a documentation issue, but want to confirm first.

Similarly, there is a reference to `CategoryId` in the response object of Add Customer. It is documented as `Unique identifier of the customer category.` however there does not appear to be endpoints for viewing/managing customer categories.

Thanks in advance for your advice.

**Comment by jirihelmich** [comment]
Hi,

there is a link in the guide that takes you to our autogenerated docs. Those include a examples of possible calls and the data you can pass. Those are complete at all times, if there is not a field you would like to use, it means that we do not support such a field.

e.g. https://www.mews.li/api/connector/v1/help/operations/UpdateCustomer

Which means, yes, currently, you are not able to modify the fields you were discussing.

Generally: https://www.mews.li/api/connector/v1/help

Also, customer categories are currently managed just by our PMS and we do not have an API for their management.

If you need an API extension, please, contact our support team, our API specialist @MeissnerJan will create an issue for you in our internal issue tracker and we will consider implementing the extension based on agreement between our companies and our common customers.

Hope it helps.
Thanks!
